# .github/workflows/deploy-kmuk.yml
name: Deploy ICP_TEST to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server & Pull
        uses: appleboy/ssh-action@master
        with:
          host: 34.234.88.162
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /data/test/webfiles
            git pull origin main
